package io.takamaka.messages.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.InputStream;
import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.RSAPrivateKeySpec;
import java.security.spec.X509EncodedKeySpec;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.takamaka.wallet.TkmCypherProviderBCRSA4096ENC256;
import io.takamaka.wallet.utils.TkmSignUtils;

/**
 * F11 P2-4 — **the first Java test in this estate that consumes a DART-produced artefact.**
 *
 * <p><b>Why this exists, and why nothing else substitutes for it.</b> Every cross-platform vector here was
 * generated by Java and verified by Dart. That one-way street is the structural reason a total interop
 * break shipped unnoticed on 2026-08-05: the platforms disagreed on the base64 alphabet of {@code enc_key},
 * and
 *
 * <ul>
 *   <li>a Dart round-trip could not see it — {@code dart:convert} decodes both alphabets, so
 *       encode→decode passes under either; and</li>
 *   <li>Java was never handed anything Dart had produced.</li>
 * </ul>
 *
 * Only a Java consumer can detect Dart <i>producer</i> drift. No quantity of same-language assertions
 * replaces one artefact crossing the boundary.
 *
 * <p><b>What is asserted.</b> RSA-OAEP is randomised, so byte-equality on the ciphertext is impossible.
 * The contract is <i>outcome agreement on a fixed corpus</i> — decrypt the Dart ciphertext and you must
 * recover the stated plaintext — plus a character-set check on the encoding. That is the same contract
 * {@code CrossPlatformVectorTest} already documents; conversation creation was simply never brought under
 * it.
 *
 * <p><b>Regenerating the vector:</b> run
 * {@code rsclient-flutter/test/generate_dart_chat_vectors_test.dart}. It writes
 * {@code Messages/src/test/resources/dart_chat_vectors.json}. The file legitimately changes on every run
 * (randomised OAEP), which is precisely why this test asserts behaviour rather than equality.
 *
 * <p>If the vector is absent the test is SKIPPED, not failed: a Java checkout without a Flutter toolchain
 * must still build. A skipped test is visible; a silently-passing one is not.
 */
public class DartProducedEncKeyVectorTest {

    private static final String VECTOR = "/dart_chat_vectors.json";
    private static final int RSA_4096_CIPHER_BYTES = 512;

    private static JsonNode vector;

    @BeforeAll
    public static void loadVector() throws Exception {
        try (InputStream in = DartProducedEncKeyVectorTest.class.getResourceAsStream(VECTOR)) {
            Assumptions.assumeTrue(in != null,
                    "dart_chat_vectors.json absent — regenerate with rsclient-flutter's "
                            + "generate_dart_chat_vectors_test.dart. Skipping, not failing: a Java-only "
                            + "checkout must still build.");
            vector = new ObjectMapper().readTree(in);
        }
    }

    /** Rebuild the Dart-side private key from the vector: modulus from the public key, d from the vector. */
    private static RSAPrivateKey dartPrivateKey() throws Exception {
        byte[] spki = TkmSignUtils.fromAnyB64ToByteArray(vector.get("encryption_public_key_url64").asText());
        RSAPublicKey pub = (RSAPublicKey) KeyFactory.getInstance("RSA")
                .generatePublic(new X509EncodedKeySpec(spki));
        BigInteger d = new BigInteger(1,
                TkmSignUtils.fromAnyB64ToByteArray(vector.get("private_exponent_b64url").asText()));
        return (RSAPrivateKey) KeyFactory.getInstance("RSA")
                .generatePrivate(new RSAPrivateKeySpec(pub.getModulus(), d));
    }

    @Test
    @DisplayName("JAVA decrypts a DART-produced enc_key back to the stated plaintext")
    public void javaDecryptsDartProducedEncKey() throws Exception {
        String encKey = vector.get("enc_key").asText();
        String expectedPlaintext = vector.get("topic_symmetric_key").asText();

        String recovered = TkmCypherProviderBCRSA4096ENC256.decryptToString(dartPrivateKey(), encKey);

        assertEquals(expectedPlaintext, recovered,
                "Java must recover exactly what Dart wrapped. This is the assertion that would have caught "
                        + "F11 on the day it was introduced.");
    }

    @Test
    @DisplayName("the DART-produced enc_key uses the agreed wire form (Base64URL, '.' padding)")
    public void dartProducerHonoursTheEncodingContract() {
        String encKey = vector.get("enc_key").asText();

        assertFalse(encKey.contains("+"), "Dart must not emit the standard alphabet");
        assertFalse(encKey.contains("/"), "Dart must not emit the standard alphabet");
        assertFalse(encKey.contains("="), "padding is '.', not '='");
        assertTrue(encKey.matches("^[A-Za-z0-9_-]+\\.{0,2}$"),
                "enc_key must be [A-Za-z0-9_-] with '.' padding — see BASE64_ENCODING_CONTRACT.md §0.1");
        assertEquals(RSA_4096_CIPHER_BYTES, TkmSignUtils.fromAnyB64ToByteArray(encKey).length,
                "and it must decode to a 512-byte RSA-4096 ciphertext");
    }

    @Test
    @DisplayName("Dart's enc_key_hash agrees with Java's own computation over the same public key")
    public void encKeyHashAgreesAcrossPlatforms() throws Exception {
        // Cheap, and it covers the neighbouring field: a hash mismatch here would mean the two platforms
        // disagree about SHA3-256 or about the public-key encoding it is taken over.
        String publicKey = vector.get("encryption_public_key_url64").asText();
        assertEquals(TkmSignUtils.Hash256B64URL(publicKey), vector.get("enc_key_hash").asText(),
                "enc_key_hash = SHA3-256-B64URL(encryption public key), identically on both platforms");
    }
}
